name: Destroy Infrastructure

on:
  workflow_dispatch:
    inputs:
      parameter-name:
        description: 'Destroy Infrastructure'
        required: true

jobs:
  destroy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.4.2

      - name: Initialize Terraform
        run: terraform init

      - name: Destroy Infrastructure
        run: terraform destroy -auto-approve
